from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

T = TypeVar("T", bound="ChatCompletionsRequestCommonLogitBiasType0")


@_attrs_define
class ChatCompletionsRequestCommonLogitBiasType0:
    """Modify the likelihood of specified tokens appearing in the completion. Accepts a json object that maps tokens
    (specified by their token ID in the tokenizer) to an associated bias value from -100 to 100. Mathematically, the
    bias is added to the logits generated by the model prior to sampling. The exact effect will vary per model, but
    values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should result
    in a ban or exclusive selection of the relevant token.

    """

    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        chat_completions_request_common_logit_bias_type_0 = cls()

        chat_completions_request_common_logit_bias_type_0.additional_properties = d
        return chat_completions_request_common_logit_bias_type_0

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
