from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, Union, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.create_chat_completion_request_function_call_type_0 import CreateChatCompletionRequestFunctionCallType0
from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.chat_completion_functions import ChatCompletionFunctions
    from ..models.chat_completion_request_message import ChatCompletionRequestMessage
    from ..models.chat_completions_request_common_logit_bias_type_0 import ChatCompletionsRequestCommonLogitBiasType0
    from ..models.create_chat_completion_request_function_call_type_1 import (
        CreateChatCompletionRequestFunctionCallType1,
    )


T = TypeVar("T", bound="CreateChatCompletionRequest")


@_attrs_define
class CreateChatCompletionRequest:
    r"""
    Attributes:
        messages (list['ChatCompletionRequestMessage']): A list of messages comprising the conversation so far. [Example
            Python code](https://github.com/openai/openai-
            cookbook/blob/main/examples/How_to_format_inputs_to_ChatGPT_models.ipynb).
        temperature (Union[None, Unset, float]): What sampling temperature to use, between 0 and 2. Higher values like
            0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.
            We generally recommend altering this or `top_p` but not both. Default: 1.0. Example: 1.
        top_p (Union[None, Unset, float]): An alternative to sampling with temperature, called nucleus sampling, where
            the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens
            comprising the top 10% probability mass are considered.
            We generally recommend altering this or `temperature` but not both. Default: 1.0. Example: 1.
        stream (Union[None, Unset, bool]): If set, partial message deltas will be sent, like in ChatGPT. Tokens will be
            sent as data-only server-sent events as they become available, with the stream terminated by a `data: [DONE]`
            message. Default: False.
        stop (Union[None, Unset, list[str], str]): Up to 4 sequences where the API will stop generating further tokens.
        max_tokens (Union[Unset, int]): The maximum number of tokens allowed for the generated answer. By default, the
            number of tokens the model can return will be (4096 - prompt tokens). Default: 4096.
        presence_penalty (Union[Unset, float]): Number between -2.0 and 2.0. Positive values penalize new tokens based
            on whether they appear in the text so far, increasing the model's likelihood to talk about new topics. Default:
            0.0.
        frequency_penalty (Union[Unset, float]): Number between -2.0 and 2.0. Positive values penalize new tokens based
            on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line
            verbatim. Default: 0.0.
        logit_bias (Union['ChatCompletionsRequestCommonLogitBiasType0', None, Unset]): Modify the likelihood of
            specified tokens appearing in the completion. Accepts a json object that maps tokens (specified by their token
            ID in the tokenizer) to an associated bias value from -100 to 100. Mathematically, the bias is added to the
            logits generated by the model prior to sampling. The exact effect will vary per model, but values between -1 and
            1 should decrease or increase likelihood of selection; values like -100 or 100 should result in a ban or
            exclusive selection of the relevant token.
        user (Union[Unset, str]): A unique identifier representing your end-user, which can help Azure OpenAI to monitor
            and detect abuse. Example: user-1234.
        functions (Union[Unset, list['ChatCompletionFunctions']]): A list of functions the model may generate JSON
            inputs for.
        function_call (Union['CreateChatCompletionRequestFunctionCallType1',
            CreateChatCompletionRequestFunctionCallType0, Unset]): Controls how the model responds to function calls. "none"
            means the model does not call a function, and responds to the end-user. "auto" means the model can pick between
            an end-user or calling a function.  Specifying a particular function via `{"name":\ "my_function"}` forces the
            model to call that function. "none" is the default when no functions are present. "auto" is the default if
            functions are present.
        n (Union[None, Unset, int]): How many chat completion choices to generate for each input message. Default: 1.
            Example: 1.
    """

    messages: list["ChatCompletionRequestMessage"]
    temperature: Union[None, Unset, float] = 1.0
    top_p: Union[None, Unset, float] = 1.0
    stream: Union[None, Unset, bool] = False
    stop: Union[None, Unset, list[str], str] = UNSET
    max_tokens: Union[Unset, int] = 4096
    presence_penalty: Union[Unset, float] = 0.0
    frequency_penalty: Union[Unset, float] = 0.0
    logit_bias: Union["ChatCompletionsRequestCommonLogitBiasType0", None, Unset] = UNSET
    user: Union[Unset, str] = UNSET
    functions: Union[Unset, list["ChatCompletionFunctions"]] = UNSET
    function_call: Union[
        "CreateChatCompletionRequestFunctionCallType1", CreateChatCompletionRequestFunctionCallType0, Unset
    ] = UNSET
    n: Union[None, Unset, int] = 1
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.chat_completions_request_common_logit_bias_type_0 import (
            ChatCompletionsRequestCommonLogitBiasType0,
        )

        messages = []
        for messages_item_data in self.messages:
            messages_item = messages_item_data.to_dict()
            messages.append(messages_item)

        temperature: Union[None, Unset, float]
        if isinstance(self.temperature, Unset):
            temperature = UNSET
        else:
            temperature = self.temperature

        top_p: Union[None, Unset, float]
        if isinstance(self.top_p, Unset):
            top_p = UNSET
        else:
            top_p = self.top_p

        stream: Union[None, Unset, bool]
        if isinstance(self.stream, Unset):
            stream = UNSET
        else:
            stream = self.stream

        stop: Union[None, Unset, list[str], str]
        if isinstance(self.stop, Unset):
            stop = UNSET
        elif isinstance(self.stop, list):
            stop = self.stop

        else:
            stop = self.stop

        max_tokens = self.max_tokens

        presence_penalty = self.presence_penalty

        frequency_penalty = self.frequency_penalty

        logit_bias: Union[None, Unset, dict[str, Any]]
        if isinstance(self.logit_bias, Unset):
            logit_bias = UNSET
        elif isinstance(self.logit_bias, ChatCompletionsRequestCommonLogitBiasType0):
            logit_bias = self.logit_bias.to_dict()
        else:
            logit_bias = self.logit_bias

        user = self.user

        functions: Union[Unset, list[dict[str, Any]]] = UNSET
        if not isinstance(self.functions, Unset):
            functions = []
            for functions_item_data in self.functions:
                functions_item = functions_item_data.to_dict()
                functions.append(functions_item)

        function_call: Union[Unset, dict[str, Any], str]
        if isinstance(self.function_call, Unset):
            function_call = UNSET
        elif isinstance(self.function_call, CreateChatCompletionRequestFunctionCallType0):
            function_call = self.function_call.value
        else:
            function_call = self.function_call.to_dict()

        n: Union[None, Unset, int]
        if isinstance(self.n, Unset):
            n = UNSET
        else:
            n = self.n

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "messages": messages,
            }
        )
        if temperature is not UNSET:
            field_dict["temperature"] = temperature
        if top_p is not UNSET:
            field_dict["top_p"] = top_p
        if stream is not UNSET:
            field_dict["stream"] = stream
        if stop is not UNSET:
            field_dict["stop"] = stop
        if max_tokens is not UNSET:
            field_dict["max_tokens"] = max_tokens
        if presence_penalty is not UNSET:
            field_dict["presence_penalty"] = presence_penalty
        if frequency_penalty is not UNSET:
            field_dict["frequency_penalty"] = frequency_penalty
        if logit_bias is not UNSET:
            field_dict["logit_bias"] = logit_bias
        if user is not UNSET:
            field_dict["user"] = user
        if functions is not UNSET:
            field_dict["functions"] = functions
        if function_call is not UNSET:
            field_dict["function_call"] = function_call
        if n is not UNSET:
            field_dict["n"] = n

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.chat_completion_functions import ChatCompletionFunctions
        from ..models.chat_completion_request_message import ChatCompletionRequestMessage
        from ..models.chat_completions_request_common_logit_bias_type_0 import (
            ChatCompletionsRequestCommonLogitBiasType0,
        )
        from ..models.create_chat_completion_request_function_call_type_1 import (
            CreateChatCompletionRequestFunctionCallType1,
        )

        d = dict(src_dict)
        messages = []
        _messages = d.pop("messages")
        for messages_item_data in _messages:
            messages_item = ChatCompletionRequestMessage.from_dict(messages_item_data)

            messages.append(messages_item)

        def _parse_temperature(data: object) -> Union[None, Unset, float]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(Union[None, Unset, float], data)

        temperature = _parse_temperature(d.pop("temperature", UNSET))

        def _parse_top_p(data: object) -> Union[None, Unset, float]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(Union[None, Unset, float], data)

        top_p = _parse_top_p(d.pop("top_p", UNSET))

        def _parse_stream(data: object) -> Union[None, Unset, bool]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(Union[None, Unset, bool], data)

        stream = _parse_stream(d.pop("stream", UNSET))

        def _parse_stop(data: object) -> Union[None, Unset, list[str], str]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, list):
                    raise TypeError()
                stop_type_1 = cast(list[str], data)

                return stop_type_1
            except:  # noqa: E722
                pass
            return cast(Union[None, Unset, list[str], str], data)

        stop = _parse_stop(d.pop("stop", UNSET))

        max_tokens = d.pop("max_tokens", UNSET)

        presence_penalty = d.pop("presence_penalty", UNSET)

        frequency_penalty = d.pop("frequency_penalty", UNSET)

        def _parse_logit_bias(data: object) -> Union["ChatCompletionsRequestCommonLogitBiasType0", None, Unset]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                logit_bias_type_0 = ChatCompletionsRequestCommonLogitBiasType0.from_dict(data)

                return logit_bias_type_0
            except:  # noqa: E722
                pass
            return cast(Union["ChatCompletionsRequestCommonLogitBiasType0", None, Unset], data)

        logit_bias = _parse_logit_bias(d.pop("logit_bias", UNSET))

        user = d.pop("user", UNSET)

        functions = []
        _functions = d.pop("functions", UNSET)
        for functions_item_data in _functions or []:
            functions_item = ChatCompletionFunctions.from_dict(functions_item_data)

            functions.append(functions_item)

        def _parse_function_call(
            data: object,
        ) -> Union["CreateChatCompletionRequestFunctionCallType1", CreateChatCompletionRequestFunctionCallType0, Unset]:
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                function_call_type_0 = CreateChatCompletionRequestFunctionCallType0(data)

                return function_call_type_0
            except:  # noqa: E722
                pass
            if not isinstance(data, dict):
                raise TypeError()
            function_call_type_1 = CreateChatCompletionRequestFunctionCallType1.from_dict(data)

            return function_call_type_1

        function_call = _parse_function_call(d.pop("function_call", UNSET))

        def _parse_n(data: object) -> Union[None, Unset, int]:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(Union[None, Unset, int], data)

        n = _parse_n(d.pop("n", UNSET))

        create_chat_completion_request = cls(
            messages=messages,
            temperature=temperature,
            top_p=top_p,
            stream=stream,
            stop=stop,
            max_tokens=max_tokens,
            presence_penalty=presence_penalty,
            frequency_penalty=frequency_penalty,
            logit_bias=logit_bias,
            user=user,
            functions=functions,
            function_call=function_call,
            n=n,
        )

        create_chat_completion_request.additional_properties = d
        return create_chat_completion_request

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
