from collections.abc import Mapping
from typing import Any, TypeVar, Union

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

T = TypeVar("T", bound="ChatCompletionRequestMessageFunctionCall")


@_attrs_define
class ChatCompletionRequestMessageFunctionCall:
    """The name and arguments of a function that should be called, as generated by the model.

    Attributes:
        name (Union[Unset, str]): The name of the function to call.
        arguments (Union[Unset, str]): The arguments to call the function with, as generated by the model in JSON
            format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by
            your function schema. Validate the arguments in your code before calling your function.
    """

    name: Union[Unset, str] = UNSET
    arguments: Union[Unset, str] = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        name = self.name

        arguments = self.arguments

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if name is not UNSET:
            field_dict["name"] = name
        if arguments is not UNSET:
            field_dict["arguments"] = arguments

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        name = d.pop("name", UNSET)

        arguments = d.pop("arguments", UNSET)

        chat_completion_request_message_function_call = cls(
            name=name,
            arguments=arguments,
        )

        chat_completion_request_message_function_call.additional_properties = d
        return chat_completion_request_message_function_call

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
